### ISSUE TITLE
As currently structured the example for data download will skip

### ISSUE THREAD

**Issue by Ezekiel-Kruglick** [taki0112/StarGAN-Tensorflow#3]
Front page recommends:
`python download.py celebA`

But download.py will skip the celebA dataset if the celebA directory is present, which it is in the repository.

I could have fixed this by issuing pull request on a version without celebA but I see reasons one might want to include that example directory so I thought I would just bring it up as an issue to be aware of. Right now if somebody clones the project and starts running the example commands this will fail to get the dataset.

**Comment by taki0112** [comment]
I modified it
Thank you
