### ISSUE TITLE
the result is reasonable?

### ISSUE THREAD

**Issue by tzhang2014** [taki0112/StarGAN-Tensorflow#4]
thanks for you sharing your work, Now, My test image is 128*128, the result as follow , is reasonable? THX!
![4](https://user-images.githubusercontent.com/19585245/41398724-dadaac0e-6fea-11e8-8fd8-56b6d82eed94.jpg)  
result:
![4](https://user-images.githubusercontent.com/19585245/41398731-e2b5e6e6-6fea-11e8-8c46-79ab48137b6a.jpg)

**Comment by taki0112** [comment]
Is is your image ? or in celebA image ?

if your image, then how did you give custom labels?

**Comment by tzhang2014** [comment]
I just run default params, just add my image to the directory of test

**Comment by taki0112** [comment]
`custom_label` means the label you assign to your image.
That is, your image is "blond hair, female, young" 
So, `custom_label` = [0, 1, 0, 0, 1]

```
python main.py --phase test --custom_label 0 1 0 0 1
```

**Comment by tzhang2014** [comment]
I got it ,Thanks
