### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by yang0817manman** [taki0112/StarGAN-Tensorflow#9]
hello,thank you for sharing your code.When I reproduced your algorithms and code, it always raises an error, I think there is something wrong that caused by tensorflow version,please help me solve this error or give me some advice,thank you very much.
error:
   from tensorflow.contrib.data import prefetch_to_device, shuffle_and_repeat, map_and_batch
ImportError: cannot import name prefetch_to_device
    train_dataset = tf.data.Dataset.from_tensor_slices((Image_data_class.train_dataset, Image_data_class.train_dataset_label, Image_data_class.train_dataset_fix_label))
AttributeError: 'module' object has no attribute 'data'

**Comment by shivam13juna** [comment]
Did you find a solution? @yang0817manman

**Comment by taki0112** [comment]
The tf version I tested is 1.8.
I think you need to upgrade.

**Comment by vivekmathema** [comment]
i tested in tensorflow-GPU 1.8 and still gives error
